import Head from 'next/head'
import apolloClient from './../apollo'
import Link from 'next/link'
import { gql } from '@apollo/client'

export default function Home({ posts }) {
  console.log(posts)
  return (
    <>
      <Head>
        <title>Jugometal app</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <h1>Hello,</h1>
        <Link href='/about'>Go to about</Link>

        {posts &&
          posts.map((data, index) => (
            <div key={data.id}>
              <h3>{data.productDetails.naslov}</h3>
              <p>{data.productDetails.prviOpis}</p>
              <hr />
            </div>
          ))}
      </div>
    </>
  )
}

export const getStaticProps = async () => {
  const { data } = await apolloClient.query({
    query: gql`
      query {
        posts(where: { categoryName: "featured" }) {
          nodes {
            productDetails {
              brend
              category
              drugiOpis
              k1
              k2
              k3
              k4
              k5
              naslov
              prviOpis
              subcategory
              slika {
                sourceUrl
              }
            }
            id
            slug
          }
        }
        mediaItems(where: { title: "jugovideo" }) {
          nodes {
            mediaItemUrl
            title
          }
        }
      }
    `,
  })

  const posts = data.posts.nodes
  const media = data.mediaItems.nodes

  return {
    props: {
      posts,
      media,
    },
  }
}

// export const getStaticProps = async () => {
//   // ovde mozes da ucinis api poziv da znas - direktno

//   const sampleData = [
//     { id: 1, name: 'Sample 1', content: 'This is sample 1' },
//     { id: 2, name: 'Sample 2', content: 'This is sample 2' },
//     { id: 3, name: 'Sample 3', content: 'This is sample 3' },
//   ]

//   return {
//     props: {
//       sampleData,
//     },
//   }
// }
