import Head from 'next/head'

import Link from 'next/link'

export default function Home({ sampleData }) {
  console.log(sampleData)
  return (
    <>
      <Head>
        <title>Jugometal app</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <h1>Hello,</h1>
        <Link href='/about'>Go to about</Link>

        {sampleData &&
          sampleData.map((data, index) => (
            <div key={data.id}>
              <h3>{data.name}</h3>
              <p>{data.content}</p>
            </div>
          ))}
      </div>
    </>
  )
}

export const getStaticProps = async () => {
  // ovde mozes da ucinis api poziv da znas - direktno

  const sampleData = [
    { id: 1, name: 'Sample 1', content: 'This is sample 1' },
    { id: 2, name: 'Sample 2', content: 'This is sample 2' },
    { id: 3, name: 'Sample 3', content: 'This is sample 3' },
  ]

  return {
    props: {
      sampleData,
    },
  }
}
